package compilation_steps.syntax;
import compilation_steps.*;
//import phase.b_syntax.ast.*; // définition de l'AST

action code {:
:};

/* Lexèmes (Tokens) */
terminal LBRACK, RBRACK, ERROR;
terminal THEORY, THEOREM, PROPOSITION;

/* Lexèmes avec valeur sémantique */


/* Variables de la grammaire et Arbre de syntaxe */
nonterminal axiom;
nonterminal theory;


/* Associativités et Priorités */


/* Règles de Productions */
axiom     ::= theory
;

theory  ::= THEORY 
;